apiVersion: v1
kind: ConfigMap
metadata:
  name: food-challenge-configmap
  labels:
    app: food-challenge-configmap
data:
  DB_HOST: "$DB_HOST"
  DB_PORT: "$DB_PORT"
  DB_USERNAME: "$DB_USERNAME"
  DB_PASSWORD: "$DB_PASSWORD"
