name: Kotlin CI with Gradle

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Install JDK 17
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-17-jdk
          java -version

      - name: Check out code
        run: |
          git clone https://github.com/${{ github.repository }}.git .
          git fetch --depth=1 origin ${{ github.ref }}

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: |
          export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
          ./gradlew build